import streamlit as st
st.title(" Skills")
st.subheader(" Programming")
st.progress(76)
st.write("Python")
st.progress(88)
st.write("JavaScript")
st.progress(75)
st.write("PHP")
st.subheader(" Design")
st.progress(96)
st.write("Canva / UI Design")
st.subheader(" Tools")
st.write("- GitHub")
st.write("- VS Code")
st.write("- Streamlit")